# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sp_user', '0003_remove_users_apps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='users',
            name='update_time',
        ),
    ]
