# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_goods', '0003_activity_activityzone_activityzonegoods_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': '首页活动', 'verbose_name_plural': '首页活动'},
        ),
        migrations.AlterModelOptions(
            name='activityzone',
            options={'verbose_name': '首页活动中心', 'verbose_name_plural': '首页活动中心'},
        ),
        migrations.AlterModelOptions(
            name='activityzonegoods',
            options={'verbose_name': '首页活动专业商品列表', 'verbose_name_plural': '首页活动专业商品列表'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '首页轮播', 'verbose_name_plural': '首页轮播'},
        ),
        migrations.AddField(
            model_name='goodssku',
            name='is_on_sale',
            field=models.BooleanField(choices=[(0, '下架'), (1, '上架')], default=0, verbose_name='是否上限'),
        ),
    ]
